import React from 'react';

export default function LegalPage() {
  return (
    <div className="relative min-h-screen bg-black text-[#e5e0d8] font-sans selection:bg-[#4a4a4a] selection:text-white">
      
      {/* Logo - Top Left */}
      <div className="absolute top-6 left-6 md:top-8 md:left-8">
        <a href="/">
          <img src="/logosix.PNG" alt="Three AI Logo" className="h-[30px] w-auto" />
        </a>
      </div>

      <div className="max-w-3xl mx-auto px-6 pt-32 pb-20 leading-relaxed space-y-16">
        
        {/* Header */}
        <header className="space-y-4 border-b border-[#333333] pb-8">
          <h1 className="text-4xl font-normal tracking-tight">Terms of Service & Privacy Policy</h1>
          <p className="text-sm text-[#a09e9a]">Last Updated: March 2026</p>
          <p className="text-base text-[#c4c1bc]">
            Three AI: "We think through so you can do."
          </p>
        </header>

        {/* Unified Terms & Privacy Content */}
        <section className="space-y-8 text-sm md:text-base text-[#c4c1bc]">
          
          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Acceptance</h3>
            <p>
              By using Three AI, you agree to these terms. If you do not agree, do not use the platform.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">What Three AI is</h3>
            <p>
              Three AI is an institutional Decision Engine. We help you visualize outcomes and improve reasoning through recursive refinement. We do not provide professional, legal, financial, or medical advice. The outputs, branches, and scenarios generated by the engine are for structural and informational purposes only.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Your account</h3>
            <p>
              You are responsible for keeping your account credentials and API keys secure. You must be at least 18 years old to use Three AI. You may not use the platform to generate illegal, harmful, or explicitly malicious branching logic.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Your data</h3>
            <p>
              Privacy is a foundational priority of our zero-leakage architecture. You own the proprietary company data and specific prompts you input into Three AI. By using the platform, you give us permission to process that data strictly to execute branching logic and deliver your decision maps. We do not sell your personal data or your decision trees to third parties. You can export or delete your data and recursive logs at any time by contacting <a href="mailto:hello@threeai.com" className="bg-gradient-to-r from-[#b372ce] to-[#5b8def] bg-clip-text text-transparent font-semibold hover:opacity-80 transition-opacity">hello@threeai.com</a>.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Intellectual Property</h3>
            <p>
              The underlying software, recursive algorithms, branding, and interface of Three AI remain our exclusive property. You retain full ownership of the specific, unique prompts and raw data you input into the system.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Limitations</h3>
            <p>
              Three AI is provided as-is. While we strive for logical accuracy, AI-generated visualizations of future outcomes are inherently probabilistic. We make no warranties regarding the absolute accuracy or real-world manifestation of the generated decision trees. We are not liable for any direct, indirect, or consequential damages resulting from actions taken based on the engine's outputs.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Termination</h3>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms. You can delete your account and associated decision data at any time by contacting <a href="mailto:hello@threeai.com" className="bg-gradient-to-r from-[#b372ce] to-[#5b8def] bg-clip-text text-transparent font-semibold hover:opacity-80 transition-opacity">hello@threeai.com</a>.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Changes</h3>
            <p>
              We may update these terms from time to time. We will notify users by email before material changes take effect.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg font-medium text-[#e5e0d8]">Contact</h3>
            <p>
              <a href="mailto:hello@threeai.com" className="bg-gradient-to-r from-[#b372ce] to-[#5b8def] bg-clip-text text-transparent font-semibold hover:opacity-80 transition-opacity">hello@threeai.com</a>
            </p>
          </div>

        </section>

        {/* Footer */}
        <footer className="pt-12 pb-8 text-sm text-[#7a7a7a] border-t border-[#333333]">
          <p>If you have any questions regarding these terms or our privacy practices, please contact our support team.</p>
          <p className="mt-2">© {new Date().getFullYear()} Three AI. All rights reserved.</p>
        </footer>

      </div>
    </div>
  );
}